// Generated by @solidjs/vite-plugin (start.env) — do not edit.
// Regenerated on every dev server and build start from env.ts.
// Keep this file (and the schema) inside your tsconfig "include".

declare module 'virtual:env/client' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
    readonly "VITE_APP_NAME": __Out<__Schema["client"]["VITE_APP_NAME"]>;
  };
  export { env };
  export default env;
}

declare module 'virtual:env/server' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
    readonly "BETTER_AUTH_SECRET": __Out<__Schema["server"]["BETTER_AUTH_SECRET"]>;
    readonly "BETTER_AUTH_URL": __Out<__Schema["server"]["BETTER_AUTH_URL"]>;
    readonly "GOOGLE_CLIENT_ID": __Out<__Schema["server"]["GOOGLE_CLIENT_ID"]>;
    readonly "GOOGLE_CLIENT_SECRET": __Out<__Schema["server"]["GOOGLE_CLIENT_SECRET"]>;
    readonly "DATABASE_URL": __Out<__Schema["server"]["DATABASE_URL"]>;
    readonly "SYNTHETIC_DELAY_MS": __Out<__Schema["server"]["SYNTHETIC_DELAY_MS"]>;
    readonly "VITE_APP_NAME": __Out<__Schema["client"]["VITE_APP_NAME"]>;
  };
  export { env };
  export default env;
}
