/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as FrameRouteImport } from './routes/_frame'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFeedsRouteImport } from './routes/api/feeds'
import { Route as FrameSettingsRouteImport } from './routes/_frame.settings'
import { Route as FrameTagsIndexRouteImport } from './routes/_frame.tags.index'
import { Route as FrameInboxIndexRouteImport } from './routes/_frame.inbox.index'
import { Route as FrameFeedsIndexRouteImport } from './routes/_frame.feeds.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as FrameTagsTagIdRouteImport } from './routes/_frame.tags.$tagId'
import { Route as FrameArticlesArticleIdRouteImport } from './routes/_frame.articles.$articleId'
import { Route as FrameInboxShortsIndexRouteImport } from './routes/_frame.inbox.shorts.index'
import { Route as FrameFeedsFeedIdIndexRouteImport } from './routes/_frame.feeds.$feedId.index'
import { Route as FrameFeedsFeedIdShortsIndexRouteImport } from './routes/_frame.feeds.$feedId.shorts.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameRoute = FrameRouteImport.update({
  id: '/_frame',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedsRoute = ApiFeedsRouteImport.update({
  id: '/api/feeds',
  path: '/api/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameSettingsRoute = FrameSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FrameRoute,
} as any)
const FrameTagsIndexRoute = FrameTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameInboxIndexRoute = FrameInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameFeedsIndexRoute = FrameFeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => FrameRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameTagsTagIdRoute = FrameTagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => FrameRoute,
} as any)
const FrameArticlesArticleIdRoute = FrameArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => FrameRoute,
} as any)
const FrameInboxShortsIndexRoute = FrameInboxShortsIndexRouteImport.update({
  id: '/inbox/shorts/',
  path: '/inbox/shorts/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameFeedsFeedIdIndexRoute = FrameFeedsFeedIdIndexRouteImport.update({
  id: '/feeds/$feedId/',
  path: '/feeds/$feedId/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameFeedsFeedIdShortsIndexRoute =
  FrameFeedsFeedIdShortsIndexRouteImport.update({
    id: '/feeds/$feedId/shorts/',
    path: '/feeds/$feedId/shorts/',
    getParentRoute: () => FrameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/settings': typeof FrameSettingsRoute
  '/api/feeds': typeof ApiFeedsRoute
  '/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/tags/$tagId': typeof FrameTagsTagIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/feeds': typeof FrameFeedsIndexRoute
  '/inbox': typeof FrameInboxIndexRoute
  '/tags': typeof FrameTagsIndexRoute
  '/feeds/$feedId': typeof FrameFeedsFeedIdIndexRoute
  '/inbox/shorts': typeof FrameInboxShortsIndexRoute
  '/feeds/$feedId/shorts': typeof FrameFeedsFeedIdShortsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/settings': typeof FrameSettingsRoute
  '/api/feeds': typeof ApiFeedsRoute
  '/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/tags/$tagId': typeof FrameTagsTagIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/feeds': typeof FrameFeedsIndexRoute
  '/inbox': typeof FrameInboxIndexRoute
  '/tags': typeof FrameTagsIndexRoute
  '/feeds/$feedId': typeof FrameFeedsFeedIdIndexRoute
  '/inbox/shorts': typeof FrameInboxShortsIndexRoute
  '/feeds/$feedId/shorts': typeof FrameFeedsFeedIdShortsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_frame': typeof FrameRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_frame/settings': typeof FrameSettingsRoute
  '/api/feeds': typeof ApiFeedsRoute
  '/_frame/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/_frame/tags/$tagId': typeof FrameTagsTagIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_frame/feeds/': typeof FrameFeedsIndexRoute
  '/_frame/inbox/': typeof FrameInboxIndexRoute
  '/_frame/tags/': typeof FrameTagsIndexRoute
  '/_frame/feeds/$feedId/': typeof FrameFeedsFeedIdIndexRoute
  '/_frame/inbox/shorts/': typeof FrameInboxShortsIndexRoute
  '/_frame/feeds/$feedId/shorts/': typeof FrameFeedsFeedIdShortsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/settings'
    | '/api/feeds'
    | '/articles/$articleId'
    | '/tags/$tagId'
    | '/api/auth/$'
    | '/feeds'
    | '/inbox'
    | '/tags'
    | '/feeds/$feedId'
    | '/inbox/shorts'
    | '/feeds/$feedId/shorts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/settings'
    | '/api/feeds'
    | '/articles/$articleId'
    | '/tags/$tagId'
    | '/api/auth/$'
    | '/feeds'
    | '/inbox'
    | '/tags'
    | '/feeds/$feedId'
    | '/inbox/shorts'
    | '/feeds/$feedId/shorts'
  id:
    | '__root__'
    | '/'
    | '/_frame'
    | '/signin'
    | '/signup'
    | '/_frame/settings'
    | '/api/feeds'
    | '/_frame/articles/$articleId'
    | '/_frame/tags/$tagId'
    | '/api/auth/$'
    | '/_frame/feeds/'
    | '/_frame/inbox/'
    | '/_frame/tags/'
    | '/_frame/feeds/$feedId/'
    | '/_frame/inbox/shorts/'
    | '/_frame/feeds/$feedId/shorts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrameRoute: typeof FrameRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiFeedsRoute: typeof ApiFeedsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame': {
      id: '/_frame'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feeds': {
      id: '/api/feeds'
      path: '/api/feeds'
      fullPath: '/api/feeds'
      preLoaderRoute: typeof ApiFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame/settings': {
      id: '/_frame/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof FrameSettingsRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/tags/': {
      id: '/_frame/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof FrameTagsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/inbox/': {
      id: '/_frame/inbox/'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof FrameInboxIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/feeds/': {
      id: '/_frame/feeds/'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FrameFeedsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame/tags/$tagId': {
      id: '/_frame/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof FrameTagsTagIdRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/articles/$articleId': {
      id: '/_frame/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof FrameArticlesArticleIdRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/inbox/shorts/': {
      id: '/_frame/inbox/shorts/'
      path: '/inbox/shorts'
      fullPath: '/inbox/shorts'
      preLoaderRoute: typeof FrameInboxShortsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/feeds/$feedId/': {
      id: '/_frame/feeds/$feedId/'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId'
      preLoaderRoute: typeof FrameFeedsFeedIdIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/feeds/$feedId/shorts/': {
      id: '/_frame/feeds/$feedId/shorts/'
      path: '/feeds/$feedId/shorts'
      fullPath: '/feeds/$feedId/shorts'
      preLoaderRoute: typeof FrameFeedsFeedIdShortsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
  }
}

interface FrameRouteChildren {
  FrameSettingsRoute: typeof FrameSettingsRoute
  FrameArticlesArticleIdRoute: typeof FrameArticlesArticleIdRoute
  FrameTagsTagIdRoute: typeof FrameTagsTagIdRoute
  FrameFeedsIndexRoute: typeof FrameFeedsIndexRoute
  FrameInboxIndexRoute: typeof FrameInboxIndexRoute
  FrameTagsIndexRoute: typeof FrameTagsIndexRoute
  FrameFeedsFeedIdIndexRoute: typeof FrameFeedsFeedIdIndexRoute
  FrameInboxShortsIndexRoute: typeof FrameInboxShortsIndexRoute
  FrameFeedsFeedIdShortsIndexRoute: typeof FrameFeedsFeedIdShortsIndexRoute
}

const FrameRouteChildren: FrameRouteChildren = {
  FrameSettingsRoute: FrameSettingsRoute,
  FrameArticlesArticleIdRoute: FrameArticlesArticleIdRoute,
  FrameTagsTagIdRoute: FrameTagsTagIdRoute,
  FrameFeedsIndexRoute: FrameFeedsIndexRoute,
  FrameInboxIndexRoute: FrameInboxIndexRoute,
  FrameTagsIndexRoute: FrameTagsIndexRoute,
  FrameFeedsFeedIdIndexRoute: FrameFeedsFeedIdIndexRoute,
  FrameInboxShortsIndexRoute: FrameInboxShortsIndexRoute,
  FrameFeedsFeedIdShortsIndexRoute: FrameFeedsFeedIdShortsIndexRoute,
}

const FrameRouteWithChildren = FrameRoute._addFileChildren(FrameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrameRoute: FrameRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiFeedsRoute: ApiFeedsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
