/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FrameRouteImport } from './routes/_frame'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiFeedsRouteImport } from './routes/api/feeds'
import { Route as FrameSettingsRouteImport } from './routes/_frame.settings'
import { Route as FrameTagsIndexRouteImport } from './routes/_frame.tags.index'
import { Route as FrameInboxIndexRouteImport } from './routes/_frame.inbox.index'
import { Route as FrameFeedsIndexRouteImport } from './routes/_frame.feeds.index'
import { Route as ApiShapesTagsRouteImport } from './routes/api/shapes/tags'
import { Route as ApiShapesSettingsRouteImport } from './routes/api/shapes/settings'
import { Route as ApiShapesFilterRulesRouteImport } from './routes/api/shapes/filter-rules'
import { Route as ApiShapesFeedsRouteImport } from './routes/api/shapes/feeds'
import { Route as ApiShapesFeedTagsRouteImport } from './routes/api/shapes/feed-tags'
import { Route as ApiShapesArticlesRouteImport } from './routes/api/shapes/articles'
import { Route as ApiShapesArticleTagsRouteImport } from './routes/api/shapes/article-tags'
import { Route as ApiMcpSplatRouteImport } from './routes/api/mcp/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as FrameTagsTagIdRouteImport } from './routes/_frame.tags.$tagId'
import { Route as FrameArticlesArticleIdRouteImport } from './routes/_frame.articles.$articleId'
import { Route as FrameInboxShortsIndexRouteImport } from './routes/_frame.inbox.shorts.index'
import { Route as FrameFeedsFeedIdIndexRouteImport } from './routes/_frame.feeds.$feedId.index'
import { Route as ApiArticlesArticleIdAudioRouteImport } from './routes/api/articles/$articleId/audio'
import { Route as FrameFeedsFeedIdShortsIndexRouteImport } from './routes/_frame.feeds.$feedId.shorts.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameRoute = FrameRouteImport.update({
  id: '/_frame',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedsRoute = ApiFeedsRouteImport.update({
  id: '/api/feeds',
  path: '/api/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameSettingsRoute = FrameSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FrameRoute,
} as any)
const FrameTagsIndexRoute = FrameTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameInboxIndexRoute = FrameInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameFeedsIndexRoute = FrameFeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => FrameRoute,
} as any)
const ApiShapesTagsRoute = ApiShapesTagsRouteImport.update({
  id: '/api/shapes/tags',
  path: '/api/shapes/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesSettingsRoute = ApiShapesSettingsRouteImport.update({
  id: '/api/shapes/settings',
  path: '/api/shapes/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesFilterRulesRoute = ApiShapesFilterRulesRouteImport.update({
  id: '/api/shapes/filter-rules',
  path: '/api/shapes/filter-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesFeedsRoute = ApiShapesFeedsRouteImport.update({
  id: '/api/shapes/feeds',
  path: '/api/shapes/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesFeedTagsRoute = ApiShapesFeedTagsRouteImport.update({
  id: '/api/shapes/feed-tags',
  path: '/api/shapes/feed-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesArticlesRoute = ApiShapesArticlesRouteImport.update({
  id: '/api/shapes/articles',
  path: '/api/shapes/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesArticleTagsRoute = ApiShapesArticleTagsRouteImport.update({
  id: '/api/shapes/article-tags',
  path: '/api/shapes/article-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSplatRoute = ApiMcpSplatRouteImport.update({
  id: '/api/mcp/$',
  path: '/api/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameTagsTagIdRoute = FrameTagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => FrameRoute,
} as any)
const FrameArticlesArticleIdRoute = FrameArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => FrameRoute,
} as any)
const FrameInboxShortsIndexRoute = FrameInboxShortsIndexRouteImport.update({
  id: '/inbox/shorts/',
  path: '/inbox/shorts/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameFeedsFeedIdIndexRoute = FrameFeedsFeedIdIndexRouteImport.update({
  id: '/feeds/$feedId/',
  path: '/feeds/$feedId/',
  getParentRoute: () => FrameRoute,
} as any)
const ApiArticlesArticleIdAudioRoute =
  ApiArticlesArticleIdAudioRouteImport.update({
    id: '/api/articles/$articleId/audio',
    path: '/api/articles/$articleId/audio',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrameFeedsFeedIdShortsIndexRoute =
  FrameFeedsFeedIdShortsIndexRouteImport.update({
    id: '/feeds/$feedId/shorts/',
    path: '/feeds/$feedId/shorts/',
    getParentRoute: () => FrameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/settings': typeof FrameSettingsRoute
  '/api/feeds': typeof ApiFeedsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/tags/$tagId': typeof FrameTagsTagIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/shapes/article-tags': typeof ApiShapesArticleTagsRoute
  '/api/shapes/articles': typeof ApiShapesArticlesRoute
  '/api/shapes/feed-tags': typeof ApiShapesFeedTagsRoute
  '/api/shapes/feeds': typeof ApiShapesFeedsRoute
  '/api/shapes/filter-rules': typeof ApiShapesFilterRulesRoute
  '/api/shapes/settings': typeof ApiShapesSettingsRoute
  '/api/shapes/tags': typeof ApiShapesTagsRoute
  '/feeds/': typeof FrameFeedsIndexRoute
  '/inbox/': typeof FrameInboxIndexRoute
  '/tags/': typeof FrameTagsIndexRoute
  '/api/articles/$articleId/audio': typeof ApiArticlesArticleIdAudioRoute
  '/feeds/$feedId/': typeof FrameFeedsFeedIdIndexRoute
  '/inbox/shorts/': typeof FrameInboxShortsIndexRoute
  '/feeds/$feedId/shorts/': typeof FrameFeedsFeedIdShortsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/settings': typeof FrameSettingsRoute
  '/api/feeds': typeof ApiFeedsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/tags/$tagId': typeof FrameTagsTagIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/shapes/article-tags': typeof ApiShapesArticleTagsRoute
  '/api/shapes/articles': typeof ApiShapesArticlesRoute
  '/api/shapes/feed-tags': typeof ApiShapesFeedTagsRoute
  '/api/shapes/feeds': typeof ApiShapesFeedsRoute
  '/api/shapes/filter-rules': typeof ApiShapesFilterRulesRoute
  '/api/shapes/settings': typeof ApiShapesSettingsRoute
  '/api/shapes/tags': typeof ApiShapesTagsRoute
  '/feeds': typeof FrameFeedsIndexRoute
  '/inbox': typeof FrameInboxIndexRoute
  '/tags': typeof FrameTagsIndexRoute
  '/api/articles/$articleId/audio': typeof ApiArticlesArticleIdAudioRoute
  '/feeds/$feedId': typeof FrameFeedsFeedIdIndexRoute
  '/inbox/shorts': typeof FrameInboxShortsIndexRoute
  '/feeds/$feedId/shorts': typeof FrameFeedsFeedIdShortsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_frame': typeof FrameRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_frame/settings': typeof FrameSettingsRoute
  '/api/feeds': typeof ApiFeedsRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_frame/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/_frame/tags/$tagId': typeof FrameTagsTagIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/shapes/article-tags': typeof ApiShapesArticleTagsRoute
  '/api/shapes/articles': typeof ApiShapesArticlesRoute
  '/api/shapes/feed-tags': typeof ApiShapesFeedTagsRoute
  '/api/shapes/feeds': typeof ApiShapesFeedsRoute
  '/api/shapes/filter-rules': typeof ApiShapesFilterRulesRoute
  '/api/shapes/settings': typeof ApiShapesSettingsRoute
  '/api/shapes/tags': typeof ApiShapesTagsRoute
  '/_frame/feeds/': typeof FrameFeedsIndexRoute
  '/_frame/inbox/': typeof FrameInboxIndexRoute
  '/_frame/tags/': typeof FrameTagsIndexRoute
  '/api/articles/$articleId/audio': typeof ApiArticlesArticleIdAudioRoute
  '/_frame/feeds/$feedId/': typeof FrameFeedsFeedIdIndexRoute
  '/_frame/inbox/shorts/': typeof FrameInboxShortsIndexRoute
  '/_frame/feeds/$feedId/shorts/': typeof FrameFeedsFeedIdShortsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/settings'
    | '/api/feeds'
    | '/oauth/consent'
    | '/articles/$articleId'
    | '/tags/$tagId'
    | '/api/auth/$'
    | '/api/mcp/$'
    | '/api/shapes/article-tags'
    | '/api/shapes/articles'
    | '/api/shapes/feed-tags'
    | '/api/shapes/feeds'
    | '/api/shapes/filter-rules'
    | '/api/shapes/settings'
    | '/api/shapes/tags'
    | '/feeds/'
    | '/inbox/'
    | '/tags/'
    | '/api/articles/$articleId/audio'
    | '/feeds/$feedId/'
    | '/inbox/shorts/'
    | '/feeds/$feedId/shorts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/settings'
    | '/api/feeds'
    | '/oauth/consent'
    | '/articles/$articleId'
    | '/tags/$tagId'
    | '/api/auth/$'
    | '/api/mcp/$'
    | '/api/shapes/article-tags'
    | '/api/shapes/articles'
    | '/api/shapes/feed-tags'
    | '/api/shapes/feeds'
    | '/api/shapes/filter-rules'
    | '/api/shapes/settings'
    | '/api/shapes/tags'
    | '/feeds'
    | '/inbox'
    | '/tags'
    | '/api/articles/$articleId/audio'
    | '/feeds/$feedId'
    | '/inbox/shorts'
    | '/feeds/$feedId/shorts'
  id:
    | '__root__'
    | '/'
    | '/_frame'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/_frame/settings'
    | '/api/feeds'
    | '/oauth/consent'
    | '/_frame/articles/$articleId'
    | '/_frame/tags/$tagId'
    | '/api/auth/$'
    | '/api/mcp/$'
    | '/api/shapes/article-tags'
    | '/api/shapes/articles'
    | '/api/shapes/feed-tags'
    | '/api/shapes/feeds'
    | '/api/shapes/filter-rules'
    | '/api/shapes/settings'
    | '/api/shapes/tags'
    | '/_frame/feeds/'
    | '/_frame/inbox/'
    | '/_frame/tags/'
    | '/api/articles/$articleId/audio'
    | '/_frame/feeds/$feedId/'
    | '/_frame/inbox/shorts/'
    | '/_frame/feeds/$feedId/shorts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrameRoute: typeof FrameRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiFeedsRoute: typeof ApiFeedsRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMcpSplatRoute: typeof ApiMcpSplatRoute
  ApiShapesArticleTagsRoute: typeof ApiShapesArticleTagsRoute
  ApiShapesArticlesRoute: typeof ApiShapesArticlesRoute
  ApiShapesFeedTagsRoute: typeof ApiShapesFeedTagsRoute
  ApiShapesFeedsRoute: typeof ApiShapesFeedsRoute
  ApiShapesFilterRulesRoute: typeof ApiShapesFilterRulesRoute
  ApiShapesSettingsRoute: typeof ApiShapesSettingsRoute
  ApiShapesTagsRoute: typeof ApiShapesTagsRoute
  ApiArticlesArticleIdAudioRoute: typeof ApiArticlesArticleIdAudioRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame': {
      id: '/_frame'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feeds': {
      id: '/api/feeds'
      path: '/api/feeds'
      fullPath: '/api/feeds'
      preLoaderRoute: typeof ApiFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame/settings': {
      id: '/_frame/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof FrameSettingsRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/tags/': {
      id: '/_frame/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof FrameTagsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/inbox/': {
      id: '/_frame/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof FrameInboxIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/feeds/': {
      id: '/_frame/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FrameFeedsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/api/shapes/tags': {
      id: '/api/shapes/tags'
      path: '/api/shapes/tags'
      fullPath: '/api/shapes/tags'
      preLoaderRoute: typeof ApiShapesTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/settings': {
      id: '/api/shapes/settings'
      path: '/api/shapes/settings'
      fullPath: '/api/shapes/settings'
      preLoaderRoute: typeof ApiShapesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/filter-rules': {
      id: '/api/shapes/filter-rules'
      path: '/api/shapes/filter-rules'
      fullPath: '/api/shapes/filter-rules'
      preLoaderRoute: typeof ApiShapesFilterRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/feeds': {
      id: '/api/shapes/feeds'
      path: '/api/shapes/feeds'
      fullPath: '/api/shapes/feeds'
      preLoaderRoute: typeof ApiShapesFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/feed-tags': {
      id: '/api/shapes/feed-tags'
      path: '/api/shapes/feed-tags'
      fullPath: '/api/shapes/feed-tags'
      preLoaderRoute: typeof ApiShapesFeedTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/articles': {
      id: '/api/shapes/articles'
      path: '/api/shapes/articles'
      fullPath: '/api/shapes/articles'
      preLoaderRoute: typeof ApiShapesArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/article-tags': {
      id: '/api/shapes/article-tags'
      path: '/api/shapes/article-tags'
      fullPath: '/api/shapes/article-tags'
      preLoaderRoute: typeof ApiShapesArticleTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/$': {
      id: '/api/mcp/$'
      path: '/api/mcp/$'
      fullPath: '/api/mcp/$'
      preLoaderRoute: typeof ApiMcpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame/tags/$tagId': {
      id: '/_frame/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof FrameTagsTagIdRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/articles/$articleId': {
      id: '/_frame/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof FrameArticlesArticleIdRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/inbox/shorts/': {
      id: '/_frame/inbox/shorts/'
      path: '/inbox/shorts'
      fullPath: '/inbox/shorts/'
      preLoaderRoute: typeof FrameInboxShortsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/feeds/$feedId/': {
      id: '/_frame/feeds/$feedId/'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId/'
      preLoaderRoute: typeof FrameFeedsFeedIdIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/api/articles/$articleId/audio': {
      id: '/api/articles/$articleId/audio'
      path: '/api/articles/$articleId/audio'
      fullPath: '/api/articles/$articleId/audio'
      preLoaderRoute: typeof ApiArticlesArticleIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame/feeds/$feedId/shorts/': {
      id: '/_frame/feeds/$feedId/shorts/'
      path: '/feeds/$feedId/shorts'
      fullPath: '/feeds/$feedId/shorts/'
      preLoaderRoute: typeof FrameFeedsFeedIdShortsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
  }
}

interface FrameRouteChildren {
  FrameSettingsRoute: typeof FrameSettingsRoute
  FrameArticlesArticleIdRoute: typeof FrameArticlesArticleIdRoute
  FrameTagsTagIdRoute: typeof FrameTagsTagIdRoute
  FrameFeedsIndexRoute: typeof FrameFeedsIndexRoute
  FrameInboxIndexRoute: typeof FrameInboxIndexRoute
  FrameTagsIndexRoute: typeof FrameTagsIndexRoute
  FrameFeedsFeedIdIndexRoute: typeof FrameFeedsFeedIdIndexRoute
  FrameInboxShortsIndexRoute: typeof FrameInboxShortsIndexRoute
  FrameFeedsFeedIdShortsIndexRoute: typeof FrameFeedsFeedIdShortsIndexRoute
}

const FrameRouteChildren: FrameRouteChildren = {
  FrameSettingsRoute: FrameSettingsRoute,
  FrameArticlesArticleIdRoute: FrameArticlesArticleIdRoute,
  FrameTagsTagIdRoute: FrameTagsTagIdRoute,
  FrameFeedsIndexRoute: FrameFeedsIndexRoute,
  FrameInboxIndexRoute: FrameInboxIndexRoute,
  FrameTagsIndexRoute: FrameTagsIndexRoute,
  FrameFeedsFeedIdIndexRoute: FrameFeedsFeedIdIndexRoute,
  FrameInboxShortsIndexRoute: FrameInboxShortsIndexRoute,
  FrameFeedsFeedIdShortsIndexRoute: FrameFeedsFeedIdShortsIndexRoute,
}

const FrameRouteWithChildren = FrameRoute._addFileChildren(FrameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrameRoute: FrameRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiFeedsRoute: ApiFeedsRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMcpSplatRoute: ApiMcpSplatRoute,
  ApiShapesArticleTagsRoute: ApiShapesArticleTagsRoute,
  ApiShapesArticlesRoute: ApiShapesArticlesRoute,
  ApiShapesFeedTagsRoute: ApiShapesFeedTagsRoute,
  ApiShapesFeedsRoute: ApiShapesFeedsRoute,
  ApiShapesFilterRulesRoute: ApiShapesFilterRulesRoute,
  ApiShapesSettingsRoute: ApiShapesSettingsRoute,
  ApiShapesTagsRoute: ApiShapesTagsRoute,
  ApiArticlesArticleIdAudioRoute: ApiArticlesArticleIdAudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
