/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FrameRouteImport } from './routes/_frame'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as FrameSettingsRouteImport } from './routes/_frame.settings'
import { Route as FrameDiscoverRouteImport } from './routes/_frame.discover'
import { Route as FrameChatRouteImport } from './routes/_frame.chat'
import { Route as FrameAiRouteImport } from './routes/_frame.ai'
import { Route as FrameTagsIndexRouteImport } from './routes/_frame.tags.index'
import { Route as FrameInboxIndexRouteImport } from './routes/_frame.inbox.index'
import { Route as FrameFeedsIndexRouteImport } from './routes/_frame.feeds.index'
import { Route as FrameTagsTagIdRouteImport } from './routes/_frame.tags.$tagId'
import { Route as FrameSettingsUsageRouteImport } from './routes/_frame.settings.usage'
import { Route as FrameSettingsGeneralRouteImport } from './routes/_frame.settings.general'
import { Route as FrameSettingsConnectionsRouteImport } from './routes/_frame.settings.connections'
import { Route as FrameArticlesArticleIdRouteImport } from './routes/_frame.articles.$articleId'
import { Route as FrameAiSessionIdRouteImport } from './routes/_frame.ai_.$sessionId'
import { Route as FrameInboxShortsIndexRouteImport } from './routes/_frame.inbox.shorts.index'
import { Route as FrameFeedsFeedIdIndexRouteImport } from './routes/_frame.feeds.$feedId.index'
import { Route as FrameTagsTagIdFeedsRouteImport } from './routes/_frame.tags.$tagId.feeds'
import { Route as FrameTagsTagIdArticlesRouteImport } from './routes/_frame.tags.$tagId.articles'
import { Route as FrameTagsTagIdShortsIndexRouteImport } from './routes/_frame.tags.$tagId.shorts.index'
import { Route as FrameFeedsFeedIdShortsIndexRouteImport } from './routes/_frame.feeds.$feedId.shorts.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameRoute = FrameRouteImport.update({
  id: '/_frame',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameSettingsRoute = FrameSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FrameRoute,
} as any)
const FrameDiscoverRoute = FrameDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => FrameRoute,
} as any)
const FrameChatRoute = FrameChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => FrameRoute,
} as any)
const FrameAiRoute = FrameAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => FrameRoute,
} as any)
const FrameTagsIndexRoute = FrameTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameInboxIndexRoute = FrameInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameFeedsIndexRoute = FrameFeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameTagsTagIdRoute = FrameTagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => FrameRoute,
} as any)
const FrameSettingsUsageRoute = FrameSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => FrameSettingsRoute,
} as any)
const FrameSettingsGeneralRoute = FrameSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => FrameSettingsRoute,
} as any)
const FrameSettingsConnectionsRoute =
  FrameSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => FrameSettingsRoute,
  } as any)
const FrameArticlesArticleIdRoute = FrameArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => FrameRoute,
} as any)
const FrameAiSessionIdRoute = FrameAiSessionIdRouteImport.update({
  id: '/ai_/$sessionId',
  path: '/ai/$sessionId',
  getParentRoute: () => FrameRoute,
} as any)
const FrameInboxShortsIndexRoute = FrameInboxShortsIndexRouteImport.update({
  id: '/inbox/shorts/',
  path: '/inbox/shorts/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameFeedsFeedIdIndexRoute = FrameFeedsFeedIdIndexRouteImport.update({
  id: '/feeds/$feedId/',
  path: '/feeds/$feedId/',
  getParentRoute: () => FrameRoute,
} as any)
const FrameTagsTagIdFeedsRoute = FrameTagsTagIdFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => FrameTagsTagIdRoute,
} as any)
const FrameTagsTagIdArticlesRoute = FrameTagsTagIdArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => FrameTagsTagIdRoute,
} as any)
const FrameTagsTagIdShortsIndexRoute =
  FrameTagsTagIdShortsIndexRouteImport.update({
    id: '/shorts/',
    path: '/shorts/',
    getParentRoute: () => FrameTagsTagIdRoute,
  } as any)
const FrameFeedsFeedIdShortsIndexRoute =
  FrameFeedsFeedIdShortsIndexRouteImport.update({
    id: '/feeds/$feedId/shorts/',
    path: '/feeds/$feedId/shorts/',
    getParentRoute: () => FrameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai': typeof FrameAiRoute
  '/chat': typeof FrameChatRoute
  '/discover': typeof FrameDiscoverRoute
  '/settings': typeof FrameSettingsRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/ai/$sessionId': typeof FrameAiSessionIdRoute
  '/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/settings/connections': typeof FrameSettingsConnectionsRoute
  '/settings/general': typeof FrameSettingsGeneralRoute
  '/settings/usage': typeof FrameSettingsUsageRoute
  '/tags/$tagId': typeof FrameTagsTagIdRouteWithChildren
  '/feeds/': typeof FrameFeedsIndexRoute
  '/inbox/': typeof FrameInboxIndexRoute
  '/tags/': typeof FrameTagsIndexRoute
  '/tags/$tagId/articles': typeof FrameTagsTagIdArticlesRoute
  '/tags/$tagId/feeds': typeof FrameTagsTagIdFeedsRoute
  '/feeds/$feedId/': typeof FrameFeedsFeedIdIndexRoute
  '/inbox/shorts/': typeof FrameInboxShortsIndexRoute
  '/feeds/$feedId/shorts/': typeof FrameFeedsFeedIdShortsIndexRoute
  '/tags/$tagId/shorts/': typeof FrameTagsTagIdShortsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ai': typeof FrameAiRoute
  '/chat': typeof FrameChatRoute
  '/discover': typeof FrameDiscoverRoute
  '/settings': typeof FrameSettingsRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/ai/$sessionId': typeof FrameAiSessionIdRoute
  '/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/settings/connections': typeof FrameSettingsConnectionsRoute
  '/settings/general': typeof FrameSettingsGeneralRoute
  '/settings/usage': typeof FrameSettingsUsageRoute
  '/tags/$tagId': typeof FrameTagsTagIdRouteWithChildren
  '/feeds': typeof FrameFeedsIndexRoute
  '/inbox': typeof FrameInboxIndexRoute
  '/tags': typeof FrameTagsIndexRoute
  '/tags/$tagId/articles': typeof FrameTagsTagIdArticlesRoute
  '/tags/$tagId/feeds': typeof FrameTagsTagIdFeedsRoute
  '/feeds/$feedId': typeof FrameFeedsFeedIdIndexRoute
  '/inbox/shorts': typeof FrameInboxShortsIndexRoute
  '/feeds/$feedId/shorts': typeof FrameFeedsFeedIdShortsIndexRoute
  '/tags/$tagId/shorts': typeof FrameTagsTagIdShortsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_frame': typeof FrameRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_frame/ai': typeof FrameAiRoute
  '/_frame/chat': typeof FrameChatRoute
  '/_frame/discover': typeof FrameDiscoverRoute
  '/_frame/settings': typeof FrameSettingsRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/_frame/ai_/$sessionId': typeof FrameAiSessionIdRoute
  '/_frame/articles/$articleId': typeof FrameArticlesArticleIdRoute
  '/_frame/settings/connections': typeof FrameSettingsConnectionsRoute
  '/_frame/settings/general': typeof FrameSettingsGeneralRoute
  '/_frame/settings/usage': typeof FrameSettingsUsageRoute
  '/_frame/tags/$tagId': typeof FrameTagsTagIdRouteWithChildren
  '/_frame/feeds/': typeof FrameFeedsIndexRoute
  '/_frame/inbox/': typeof FrameInboxIndexRoute
  '/_frame/tags/': typeof FrameTagsIndexRoute
  '/_frame/tags/$tagId/articles': typeof FrameTagsTagIdArticlesRoute
  '/_frame/tags/$tagId/feeds': typeof FrameTagsTagIdFeedsRoute
  '/_frame/feeds/$feedId/': typeof FrameFeedsFeedIdIndexRoute
  '/_frame/inbox/shorts/': typeof FrameInboxShortsIndexRoute
  '/_frame/feeds/$feedId/shorts/': typeof FrameFeedsFeedIdShortsIndexRoute
  '/_frame/tags/$tagId/shorts/': typeof FrameTagsTagIdShortsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai'
    | '/chat'
    | '/discover'
    | '/settings'
    | '/oauth/consent'
    | '/ai/$sessionId'
    | '/articles/$articleId'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/usage'
    | '/tags/$tagId'
    | '/feeds/'
    | '/inbox/'
    | '/tags/'
    | '/tags/$tagId/articles'
    | '/tags/$tagId/feeds'
    | '/feeds/$feedId/'
    | '/inbox/shorts/'
    | '/feeds/$feedId/shorts/'
    | '/tags/$tagId/shorts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ai'
    | '/chat'
    | '/discover'
    | '/settings'
    | '/oauth/consent'
    | '/ai/$sessionId'
    | '/articles/$articleId'
    | '/settings/connections'
    | '/settings/general'
    | '/settings/usage'
    | '/tags/$tagId'
    | '/feeds'
    | '/inbox'
    | '/tags'
    | '/tags/$tagId/articles'
    | '/tags/$tagId/feeds'
    | '/feeds/$feedId'
    | '/inbox/shorts'
    | '/feeds/$feedId/shorts'
    | '/tags/$tagId/shorts'
  id:
    | '__root__'
    | '/'
    | '/_frame'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_frame/ai'
    | '/_frame/chat'
    | '/_frame/discover'
    | '/_frame/settings'
    | '/oauth/consent'
    | '/_frame/ai_/$sessionId'
    | '/_frame/articles/$articleId'
    | '/_frame/settings/connections'
    | '/_frame/settings/general'
    | '/_frame/settings/usage'
    | '/_frame/tags/$tagId'
    | '/_frame/feeds/'
    | '/_frame/inbox/'
    | '/_frame/tags/'
    | '/_frame/tags/$tagId/articles'
    | '/_frame/tags/$tagId/feeds'
    | '/_frame/feeds/$feedId/'
    | '/_frame/inbox/shorts/'
    | '/_frame/feeds/$feedId/shorts/'
    | '/_frame/tags/$tagId/shorts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrameRoute: typeof FrameRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame': {
      id: '/_frame'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frame/settings': {
      id: '/_frame/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof FrameSettingsRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/discover': {
      id: '/_frame/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof FrameDiscoverRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/chat': {
      id: '/_frame/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof FrameChatRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/ai': {
      id: '/_frame/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof FrameAiRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/tags/': {
      id: '/_frame/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof FrameTagsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/inbox/': {
      id: '/_frame/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof FrameInboxIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/feeds/': {
      id: '/_frame/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FrameFeedsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/tags/$tagId': {
      id: '/_frame/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof FrameTagsTagIdRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/settings/usage': {
      id: '/_frame/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof FrameSettingsUsageRouteImport
      parentRoute: typeof FrameSettingsRoute
    }
    '/_frame/settings/general': {
      id: '/_frame/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof FrameSettingsGeneralRouteImport
      parentRoute: typeof FrameSettingsRoute
    }
    '/_frame/settings/connections': {
      id: '/_frame/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof FrameSettingsConnectionsRouteImport
      parentRoute: typeof FrameSettingsRoute
    }
    '/_frame/articles/$articleId': {
      id: '/_frame/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof FrameArticlesArticleIdRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/ai_/$sessionId': {
      id: '/_frame/ai_/$sessionId'
      path: '/ai/$sessionId'
      fullPath: '/ai/$sessionId'
      preLoaderRoute: typeof FrameAiSessionIdRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/inbox/shorts/': {
      id: '/_frame/inbox/shorts/'
      path: '/inbox/shorts'
      fullPath: '/inbox/shorts/'
      preLoaderRoute: typeof FrameInboxShortsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/feeds/$feedId/': {
      id: '/_frame/feeds/$feedId/'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId/'
      preLoaderRoute: typeof FrameFeedsFeedIdIndexRouteImport
      parentRoute: typeof FrameRoute
    }
    '/_frame/tags/$tagId/feeds': {
      id: '/_frame/tags/$tagId/feeds'
      path: '/feeds'
      fullPath: '/tags/$tagId/feeds'
      preLoaderRoute: typeof FrameTagsTagIdFeedsRouteImport
      parentRoute: typeof FrameTagsTagIdRoute
    }
    '/_frame/tags/$tagId/articles': {
      id: '/_frame/tags/$tagId/articles'
      path: '/articles'
      fullPath: '/tags/$tagId/articles'
      preLoaderRoute: typeof FrameTagsTagIdArticlesRouteImport
      parentRoute: typeof FrameTagsTagIdRoute
    }
    '/_frame/tags/$tagId/shorts/': {
      id: '/_frame/tags/$tagId/shorts/'
      path: '/shorts'
      fullPath: '/tags/$tagId/shorts/'
      preLoaderRoute: typeof FrameTagsTagIdShortsIndexRouteImport
      parentRoute: typeof FrameTagsTagIdRoute
    }
    '/_frame/feeds/$feedId/shorts/': {
      id: '/_frame/feeds/$feedId/shorts/'
      path: '/feeds/$feedId/shorts'
      fullPath: '/feeds/$feedId/shorts/'
      preLoaderRoute: typeof FrameFeedsFeedIdShortsIndexRouteImport
      parentRoute: typeof FrameRoute
    }
  }
}

interface FrameSettingsRouteChildren {
  FrameSettingsConnectionsRoute: typeof FrameSettingsConnectionsRoute
  FrameSettingsGeneralRoute: typeof FrameSettingsGeneralRoute
  FrameSettingsUsageRoute: typeof FrameSettingsUsageRoute
}

const FrameSettingsRouteChildren: FrameSettingsRouteChildren = {
  FrameSettingsConnectionsRoute: FrameSettingsConnectionsRoute,
  FrameSettingsGeneralRoute: FrameSettingsGeneralRoute,
  FrameSettingsUsageRoute: FrameSettingsUsageRoute,
}

const FrameSettingsRouteWithChildren = FrameSettingsRoute._addFileChildren(
  FrameSettingsRouteChildren,
)

interface FrameTagsTagIdRouteChildren {
  FrameTagsTagIdArticlesRoute: typeof FrameTagsTagIdArticlesRoute
  FrameTagsTagIdFeedsRoute: typeof FrameTagsTagIdFeedsRoute
  FrameTagsTagIdShortsIndexRoute: typeof FrameTagsTagIdShortsIndexRoute
}

const FrameTagsTagIdRouteChildren: FrameTagsTagIdRouteChildren = {
  FrameTagsTagIdArticlesRoute: FrameTagsTagIdArticlesRoute,
  FrameTagsTagIdFeedsRoute: FrameTagsTagIdFeedsRoute,
  FrameTagsTagIdShortsIndexRoute: FrameTagsTagIdShortsIndexRoute,
}

const FrameTagsTagIdRouteWithChildren = FrameTagsTagIdRoute._addFileChildren(
  FrameTagsTagIdRouteChildren,
)

interface FrameRouteChildren {
  FrameAiRoute: typeof FrameAiRoute
  FrameChatRoute: typeof FrameChatRoute
  FrameDiscoverRoute: typeof FrameDiscoverRoute
  FrameSettingsRoute: typeof FrameSettingsRouteWithChildren
  FrameAiSessionIdRoute: typeof FrameAiSessionIdRoute
  FrameArticlesArticleIdRoute: typeof FrameArticlesArticleIdRoute
  FrameTagsTagIdRoute: typeof FrameTagsTagIdRouteWithChildren
  FrameFeedsIndexRoute: typeof FrameFeedsIndexRoute
  FrameInboxIndexRoute: typeof FrameInboxIndexRoute
  FrameTagsIndexRoute: typeof FrameTagsIndexRoute
  FrameFeedsFeedIdIndexRoute: typeof FrameFeedsFeedIdIndexRoute
  FrameInboxShortsIndexRoute: typeof FrameInboxShortsIndexRoute
  FrameFeedsFeedIdShortsIndexRoute: typeof FrameFeedsFeedIdShortsIndexRoute
}

const FrameRouteChildren: FrameRouteChildren = {
  FrameAiRoute: FrameAiRoute,
  FrameChatRoute: FrameChatRoute,
  FrameDiscoverRoute: FrameDiscoverRoute,
  FrameSettingsRoute: FrameSettingsRouteWithChildren,
  FrameAiSessionIdRoute: FrameAiSessionIdRoute,
  FrameArticlesArticleIdRoute: FrameArticlesArticleIdRoute,
  FrameTagsTagIdRoute: FrameTagsTagIdRouteWithChildren,
  FrameFeedsIndexRoute: FrameFeedsIndexRoute,
  FrameInboxIndexRoute: FrameInboxIndexRoute,
  FrameTagsIndexRoute: FrameTagsIndexRoute,
  FrameFeedsFeedIdIndexRoute: FrameFeedsFeedIdIndexRoute,
  FrameInboxShortsIndexRoute: FrameInboxShortsIndexRoute,
  FrameFeedsFeedIdShortsIndexRoute: FrameFeedsFeedIdShortsIndexRoute,
}

const FrameRouteWithChildren = FrameRoute._addFileChildren(FrameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrameRoute: FrameRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
